### ISSUE TITLE
Reloading changes white cards

### ISSUE THREAD

**Issue by Javernus** [jappe999/project-cards#10]
When you join a game and you reload, it redraws the cards instead of giving you the same cards.

**Comment by coffeebrick** [comment]
Yeah, this is (for now) intented behaviour. Will change it in the next version!

**Comment by jappe999** [comment]
#13

**Comment by coffeebrick** [comment]
@Javernus could you take a look at PR I referenced?

**Comment by Javernus** [comment]
Okay, good to know.
