### ISSUE TITLE
Black card isn't always visible

### ISSUE THREAD

**Issue by coffeebrick** [jappe999/project-cards#20]
The problem is in the authentication. The bearer token isn't sent with the initial connection when the user isn't logged in yet. This causes all the gateway endpoints to fail.

## Expected Behavior

When joining a game and playing it, the black card should always be visible.

## Current Behavior

Sometimes I get a blank black card. When I reload the page I do get the black card.

## Possible Solution

The socket connection should only be made when the user is authenticated.

## Steps to Reproduce (for bugs)

1. Open a new browser session.
2. Login
3. Choose a game
4. See that there is no text for the black card.
5. Reload the page.
6. The text for the black card has appeared.

## Context

This is very annoying when playing the game without a browser frame on mobile.

## Your Environment

- Version used: NA
- Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 70, Chrome 76 Node.JS 10.0
- Operating System and version (desktop or mobile): Pop OS! 19.04

**Comment by jappe999** [comment]
Fixed in PR #22

**Comment by coffeebrick** [comment]
Fixed in PR #22
