### ISSUE TITLE
Played cards should be face-down until flipped by the Card Czar

### ISSUE THREAD

**Issue by Xiithrian** [jappe999/project-cards#58]
## Expected Behavior

Played cards shouldn't be readable, until the Czar clicks on them to flip them over.

## Current Behavior

Anyone who played their cards can read all other played cards. When all cards are played, Czar gets to see all cards at once. 

## Possible Solution

Make a design for face-down cards and implement behavior for flipping cards as Card Czar.

## Steps to Reproduce (for bugs)

1. Start a game with several players
2. Play cards. The cards played by others are readable.
3. As Czar: wait for all cards to be played; they're readable all at once.

## Context

It's kinda immersion breaking when some players can read specific cards before others do. In the physical game everyone gets this information at the same time, which is more suspenseful and interesting.

## Your Environment

- Version used: 1.0

**Comment by coffeebrick** [comment]
Maybe it's better if the current behavior for the card Czar is implemented for the other players as well. That way you get closer to the way a real game of cards against humanity is played.

1. No cards are shown to the Czar.
2. While players choose their cards, blank cards appear on the screen of the Czar. This also happens for the players, but they can only see the text of their own cards.
3. When all players have chosen their cards, the cards automatically flip over and can be read by read by every player.

The only difference with the current implementation is that the cards are only chosen when every player submitted their cards.

**Comment by Xiithrian** [comment]
That's pretty much what I'm suggesting, except I wouldn't flip all cards at the same time. That's not how a real game works. In a real game, Czar flips one card at a time and everyone is focused on this card only.
